### ISSUE TITLE
Introduce a PR checklist

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy#145]
I'd like to introduce a new "policy" for PRs. Each time a PR is submitted a checklist list something like:

- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality is it tested? Do public methods/classes have docstrings? Did you add an explanation to the online documentation?
- [ ] Is it well formatted? (list ways to run linters)
- [ ] Is it documented in the Release Notes? 

will be added to the top of the PR.

This will help us prevent pushing in code to the master branch that is in a less than adequate state.

It may also help stall PR too.

We can have a checklist for examples too, that is based on the guidelines Jim has been developing.

**Comment by moorepants** [comment]
@pydy/pydy-developers I'd love some feedback on this.

**Comment by chrisdembia** [comment]
Linters can easily be run on travis, and we can make the travis test fail if the linter fails. Clarify "mergeable" to mean "no merge conflicts". 

Add "have all reviewer comments been addressed?"

These guidelines could be placed in CONTRIBUTING.md.

**Comment by jcrist** [comment]
I'm not sure I like the idea of putting a checklist at the top of each PR. I like how SymPy does it, with specific developer directions in CONTRIBUTING.md. Some of these can be checked automatically by travis, and the rest should be common sense for anyone reviewing a PR before merging. I vote we just add linting to travis, and make a nice checklist in contributing.md.

**Comment by moorepants** [comment]
Why don't you like the idea? To me, it seems very simple. I also proposed this on the SymPy email list and expect many people to reject it. But my guess is that the rejections are rooted in things like "more rules = bad" than any technical reasons that this will not work. When I've worked at companies that produced a product, things like this were almost always in place. You could tell the assembly line "don't forget any nuts" or you can have them run through a checklist to ensure each machine has all the nuts. Seems like a minor inconvenience for what is gained.

**Comment by moorepants** [comment]
This checklist, for example, may have prevented the viz package from being in a broken state in the master branch and @jcrist's plans to use the viz stuff in his presentation wouldn't have been foiled.

**Comment by chrisdembia** [comment]
Well there's no harm in trying something out. I suggest the PR-maker has to copy the checklist into the PR, and it's the responsibility of reviewers to check off the boxes.

**Comment by moorepants** [comment]
Yes, I think it can be worth a try. It is easy enough to stop doing it. I'll open a PR to add this list to a CONTRIBUTING file and we can modify it. Then if there are no major complaints we can try it out for a while.

**Comment by chrisdembia** [comment]
Make sure to add the checklist to your own PR :p

**Comment by moorepants** [comment]
:)

**Comment by hazelnusse** [comment]
I like the idea of the checklist.  I just read The Checklist Manifesto
<http://www.amazon.com/The-Checklist-Manifesto-Things-Right/dp/0312430000> and
while most surgeon's pushed back to such kinds of checklists at first, it
has been shown to ultimately save lives.  I think we should try to save
lives in PyDy as well :)

Luke

On Fri, Mar 13, 2015 at 4:11 PM, Jason K. Moore <notifications@github.com>
wrote:

> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydy/pydy/issues/145#issuecomment-79518105>.
>



-- 
I have always wished that my computer would be as easy to use as my
telephone. My wish has come true. I no longer know how to use my telephone.
- Bjarne Stroustrup

**Comment by jcrist** [comment]
I agree with the usefulness of checklists, and would be willing to try one out to see if it helps. My main concern is that a checklist could become out of sync with the PR. Suppose a reviewer checks one of the boxes (passes linting, for example), and then a new commit is pushed. To ensure it still passes linting, you'd have to check, but the PR checklist already says it does. So do you always trust that the checklist is up to date (missing this), or never trust that it is? If we never trust the checklist to be accurately checked, then all this gets us is a reminder of what needs to be done, rather than a confirmation that it is. This is still useful, but needs to be considered.

**Comment by moorepants** [comment]
That's a good point. I'm not sure that is how it will happen in practice though. We'd have to try it so see if people will actually uncheck if their local testing starts to fail. I see how several of the things we check are based on iterative processes. Same goes for the reviewers' comments. I can add a new comment after the list has been checked. But it would be up to me to uncheck the box when adding a new comment.
