### ISSUE TITLE
Checklist(pending) for Midterm evaluations - Tarun Gaba

### ISSUE THREAD

**Issue by tarzzz** [pydy/pydy#68]
Here is the checklist of deliverables upto the midterm evaluations for my project.
@chrisdembia @moorepants Please feel free to add any implementation or enhancement I might have missed.
- [x] Make Scene objects editable and save-able(to file) **priority**
- [x] Fix animation bug(animations behaving in un-expected manner)
- [x] Fix prototype.js(conflicting with IPython's native jQuery) **priority**
- [x] implement _materials_ from Javascript side **priority**
- [ ] Allow CAD meshes to be added **priority**
- [x] Write Docstrings.
- [x] Clean up Code.
- [x] write tests.
- [x] Destroy old objects when loading a new one(currently old ones are appended to)
- [x] Scrolling the slider should take to that particular point in animation!

**P.S:** Since this is a lot of work for 4 days(before midterm evals start), focus will be to work on **priority** issues before the midterm evals deadline.
Rest can be implemented alongside after midterm evals. Does that sound good?
